"""
This code generates HTML page with date and time using FAST API."""
from fastapi import FastAPI, Request
from fastapi.responses import HTMLResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates

app = FastAPI()

app.mount("/static", StaticFiles(directory="static"), name="static")

templates = Jinja2Templates(directory="templates")


@app.get("/", response_class=HTMLResponse)
async def read_item(request: Request):
    """
    :param request: GET request from browsers
    :return: HTML page with date and time generated by JS code snippet
    """
    return templates.TemplateResponse("date_time.html", {"request": request})
