- name: Ensure Pip is installed.
  become: true
  package:
    name: "python3-pip"
    state: present

- name: Ensure directory for application
  become: true
  file:
    owner: "{{ ansible_user_id }}"
    path: /opt/python_app/
    state: directory
    mode: 0755

- name: Install docker libraries
  become: true
  pip:
    name:
      - docker
      - docker-compose
    state: present

- name: Copy docker-compose
  template:
    src: docker-compose.yml.j2
    dest: /opt/python_app/docker-compose.yml
    mode: u=rw,g=r,o=r

- name: Run docker-compose
  become: true
  community.docker.docker_compose:
    pull: true
    recreate: always
    state: present
    project_src: /opt/python_app/