name: Run ansible playbook
on:
  workflow_run:
    workflows: [Publish Docker image]
    types:
      - completed

jobs:
  run_playbook:
    runs-on: ubuntu-latest
    steps:
    - name: change directory
      run: ls

    - name: Run playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        # Required, playbook filepath
        playbook: setup_app.yml
        # Optional, SSH private key
        key: ${{secrets.SSH_PRIVATE_KEY}}