name: Run terraform
on:
  workflow_run:
    workflows: [Publish Docker image]
    types:
      - completed

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Decrypt secrets
        uses:  minddocdev/decrypt-action@master
        with:
          files: terraform/aws_key.pub.gpg, terraform/aws_key.gpg, terraform/techtask.crt.gpg, terraform/techtask.key.gpg
          passphrase: ${{ secrets.SECRETS_PASSPHRASE }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Apply
        env:
          DOCKER_IMAGE_TAG: ${{ steps.commit.outputs.short }}
        run: terraform apply -auto-approve -input=false